var fullName = "Broseph Code";
var firstName = fullName.slice(0, 3);
console.log(firstName);
var lastName = fullName.slice(4, 8);
console.log(lastName);
lastName = fullName.slice(4);
console.log(lastName);
var firstChar = fullName.slice(0, 1);
console.log(firstChar);
var lastChar = fullName.slice(-1);
console.log(lastChar);
firstName = fullName.slice(0, fullName.indexOf(" "));
console.log(firstName);
lastName = fullName.slice(fullName.indexOf(" ") + 1);
console.log(lastName);
// console.log(firstChar);
var email = "Bro1@gmail.com";
var username = email.slice(0, email.indexOf("@"));
var extension = email.slice(email.indexOf("@"));
console.log(username);
console.log(extension);
