var x = 3.2;
var y = 2;
var z = 1;
z = Math.round(x);
console.log(z);
z = Math.floor(x);
console.log(z);
z = Math.ceil(x);
console.log(z);
z = Math.pow(x, y);
console.log(z);
z = Math.sqrt(x);
console.log(z);
z = Math.log(x);
console.log(z);
z = Math.sin(x);
console.log(z);
z = Math.cos(x);
console.log(z);
z = Math.tan(x);
console.log(z);
z = Math.abs(x);
console.log(z);
var max = Math.max(x, y, z);
var min = Math.min(x, y, z);
console.log(max);
console.log(min);
