var age = 25;
var price = 10.99;
var gpa = 2.1;
var firstName = "Jehan";
var favouriteFood = "Pizza";
var email = "jhasan0122@gmail.com";
var online = true;
var student = false;
var fullBName = firstName + "Hasan";
console.log("You are ".concat(age, " years old"));
console.log("The price is $".concat(price));
console.log("Your cgpa is ".concat(gpa));
console.log(typeof firstName);
console.log(firstName);
console.log("Your name is ".concat(firstName));
console.log("You like ".concat(favouriteFood));
console.log("Your email is ".concat(email));
console.log(typeof online);
console.log("Bro is online: ".concat(online));
document.getElementById('p1').textContent = "Fullname :".concat(fullBName);
document.getElementById('p2').textContent = "Age :".concat(age);
document.getElementById('p3').textContent = "CGPA :".concat(gpa);
